spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/g132store_magazine?currentSchema=store"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
